Added Helm charts for Hardware Classification
Mirantis/metal3-helm-chart pull request #11
Opened 2020-05-21 07:35 UTC by sharajat

This PR is regarding Helm charts for Hardware-classification-controller. 
https://github.com/metal3-io/hardware-classification-controller

2020-05-21 08:35 UTC, digambar15 requested changes

2020-05-21 08:35 UTC, digambar15 commented on charts/hardware-classification/values.yaml
> +namespace: hcc-system
hardware-classification

2020-05-21 08:35 UTC, digambar15 commented on values.yaml
> +  namespace: hcc-system
Ditto!

2020-05-25 07:01 UTC, sharajat commented on charts/hardware-classification/values.yaml
> +namespace: hcc-system
Changed namespace.

2020-05-25 07:01 UTC, sharajat commented on values.yaml
> +  namespace: hcc-system
changed namespace.

2020-06-05 16:13 UTC, digambar15 commented
looks good

2020-06-05 16:14 UTC, digambar15 commented
/assign @maelk @dhellmann

2020-06-12 06:26 UTC, digambar15 approved these changes
Looks Good

2020-06-12 06:55 UTC, maelk commented
From https://github.com/metal3-io/metal3-helm-chart/blob/master/OWNERS , it looks like only two people have the approval rights for the review.

2020-06-12 06:56 UTC, maelk commented
aside of hard-coding the limits, this looks ok for me.

2020-06-16 14:52 UTC, sharajat commented
/assign @ogelbukh

2020-07-02 23:28 UTC, ogelbukh approved these changes

2020-07-02 23:29 UTC, ogelbukh commented
/lgtm

2020-07-02 23:29 UTC, merged