Add ability use external baremetal-operator configs
Mirantis/metal3-helm-chart pull request #8
Opened 2020-01-21 07:37 UTC by jingvar

Introduce external config files and entry points for containers in baremetal-operator.  It can be applied to containers witch require custom configuration parameters.

2020-01-22 06:18 UTC, jingvar commented
/assign @ogelbukh

2020-01-22 09:31 UTC, dukov requested changes

2020-01-22 09:31 UTC, dukov commented on charts/baremetal-operator/templates/ironic.yaml
> +              {{- if or .Values.ironic.config_override.httpd }}
remove 'or'

2020-01-22 13:47 UTC, jingvar commented on charts/baremetal-operator/templates/ironic.yaml
> +              {{- if or .Values.ironic.config_override.httpd }}
Done

2020-01-22 13:48 UTC, dukov approved these changes

2020-01-27 11:07 UTC, jingvar commented
/assign @ogelbukh

2020-05-28 15:08 UTC, closed without merging