Update to be able to set ironic_fast_track
Mirantis/metal3-helm-chart pull request #9
Opened 2020-01-21 08:16 UTC by yakiyoshi

I got error messages on ironic container that details are [here](https://github.com/metal3-io/ironic-image/issues/132).
About disabling fasttrack discussed in [ironic-image project issue#130](https://github.com/metal3-io/ironic-image/pull/130).
The Charts may need to set ironic_fast_track environment value on the ironic container.

2020-01-22 06:15 UTC, jingvar commented
I have a big pull request with fast_track and some changes of variables structure. Could you make your request according to this?

2020-01-22 08:11 UTC, dukov approved these changes

2020-01-22 08:21 UTC, dukov requested changes

2020-01-22 08:21 UTC, dukov commented on charts/baremetal-operator/templates/ironic.yaml
> +              value: "{{ .Values.ironic.ironic_conf.ironic_fast_track }}"
use `.Values.ironic.ironic_conf.ironic_fast_track | quote` instead of double quotes like it's implemented in HTTP_PORT variable above

2020-01-23 02:53 UTC, yakiyoshi commented
@jingvar Thank you for the change. I'll withdraw my request, because I confirmed the fix to be able to fit the fast_track to an environment in your request.

2020-01-23 02:53 UTC, closed without merging